### PR TITLE
Changes from adding automated parameter conversion

### PR DESCRIPTION
**Pull request by mrshirts**
- Introduced automatically-generated input files for CHARMM, DESMOND, and LAMMPS
- Reorganizes naming convention of simulation structure files
- Provides energy comparison of all automatically generated files in simulation_comparison_input

### CODE REVIEW

**Comment by mrshirts** [comment]
One thing to be resolved: there are now two sets of gromacs files in vacuum -- the original ones that were in topgro.tar.gz (now in gromacs_original.tar.gz), and new ones in gromacs.tar.gz that were generated in the automated process conversion.  The new ones DO have full energy validation of their conversion, but are not the files that were used in the free energy calculations.  So I don't know what the best call is for distributing/labeling those two sets of files.

**Comment by davidlmobley** [comment]
@mrshirts - relating to the two sets of GROMACS files, what is the EXACT procedure you used to generate these? (ParmEd version, for example?) Have you diffed any of them against the original vacuum files?
Naively, I would hope that we generated them with the same or equivalent ParmEd versions so they would actually be identical, but if they are not, then we will have to retain both sets and label them separately (and I'll need to explain exactly where yours came from/why they are included).

**Comment by mrshirts** [comment]
I can set up an automated energy check on the two sets (maybe by late tonight, not earlier).  In terms of where they came from, that's documented in the instructions; InterMol calling ParmEd and doing amber ==> GROMACS.  So they should be the same energies, but there are still some bugs in ParmEd.

**Comment by davidlmobley** [comment]
@mrshirts - which ParmEd version? 
Bugs: Do you mean there are bugs relating to AMBER-> GROMACS? I have not been aware of any but if you are, that would be important to know.

**Comment by mrshirts** [comment]
2.73. I'm saying with 650 files, unless you ran the energies for both of them and checked, there could be bugs.  We found a couple in Amber->Charmm conversion when running FreeSolv. (actually, another was introduced between 2.73 and master that still needs to be resolved).  If you already checked all 650 energies amber->gromacs, then there probably aren't any differences.

**Comment by mrshirts** [comment]
Here's some output of a comparison -- attaching the tools so you can query things a bit more.
New .gro files are used for all comparisons, but different .top files.

[FreeSolvCompare.zip](https://github.com/MobleyLab/FreeSolv/files/887698/FreeSolvCompare.zip)
Upshot:
- for almost all molecules, only Coulomb is really different. Only one molecule (mobley_7378987 1,3,7-trimethylpurine-2,6-dione) has bonded energies bigger than ~0.001 kJ/mol (energies for that one are 0.01 kJ/mol, due to angles), most less than 0.0005 kJ/mol.
- 96% of Coulomb total differences are between -0.05 and 0.05 kJ/mol. A few are in the range +/- 0.1-0.2 kJ/mol. Most of that is coulomb-14 (because that term is larger).  Haven't analyzed why those yet.

**Comment by davidlmobley** [comment]
OK, thanks, @mrshirts . So I think the upshot of comparing your GROMACS topologies to ours (which, for the record, as per our discussion elsewhere, were generated from AMBER via acpype prior to our migration to ParmEd) is that the energies are rather similar except for the differences one would expect from Coulomb interactions due to charges which are rounded differently. So I will make sure to clearly note the differences between these two sets of files in the README.md documents.

I'm going to go ahead and merge this, and then go through and see if any minor cleanup is needed and bring it in in a separate PR.

**Pull request merged**
